### ISSUE TITLE
Problem with Access Denied for loki-compactor pod v4.0.1

### ISSUE THREAD

**Issue by armandleopold** [camptocamp/devops-stack-module-loki-stack#93]
There is a problem with the loki-compactor pod when installing from scratch on OVHCloud (don't think it's related) i get an "Access Denied", every other components of the stack works.

**Comment by lentidas** [comment]
Hi @armandleopold! :wave:

Do you have any more information? Which component is the compactor trying to access to get the "Access Denied". Is it the bucket? Could you share some logs with us?

**Comment by armandleopold** [comment]
It was related to the minio S3 credentials not properly passed from the config.
My bad, it works now
